# Generated by Django 2.1.4 on 2018-12-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='c_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
