# Generated by Django 2.1.4 on 2018-12-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181225_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='created_date',
        ),
    ]
