# Generated by Django 2.1.4 on 2018-12-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181225_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_email',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
