# Generated by Django 2.1.4 on 2018-12-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181225_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post2contents', to='blog.Category'),
        ),
    ]
