# Generated by Django 2.1.4 on 2018-12-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181225_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
