# Generated by Django 2.1.4 on 2018-12-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181225_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Content'),
        ),
    ]
