# Generated by Django 2.1.4 on 2018-12-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181225_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='post',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
